### ISSUE TITLE
Update/Set multiple searchParams at once

### ISSUE THREAD

**Issue by sgoerres** [howesteve/elegua#11]
Hi,

I am currently migrating an old web app to Svelte and came across this nice and easy routing library.
Thanks to the inclusion of searchParams this is very much the thing I was looking for without any additional fuzz.

My application makes some use of date-ranges and, due to some backward compatibility I need to have at the moment, these are handled via two URL query parameters (start and end).
When utilizing $searchParams and setting one after the other I basically get the "forward" movement I want: page is updating based on both new values. Though, internally, it is pushing two states.
This becomes apparent when going back via browser history: I basically get two steps: one for changing parameter 1, one for changing parameter 2.

I found a workaround using "goto":
```
      const u = new URL(window.location.href);
      u.searchParams.set('start', formatDate(newStart));
      u.searchParams.set('end', formatDate(newEnd));
      goto(u);
```

This provides the behavior I intend. 

I was wondering if this is an edge case with my application and I should leave it as such or if there is another way (e.g. adding a custom $searchParams setter) to improve elegua here?

If my explanations were unclear let me know and I will try to improve.

Best regards,
Sven

**Comment by howesteve** [comment]
Glad you liked elegua and thanks for reporting this.

See, I implemented `$searchParams.set()` as an easier shortcut helper for the most common case which I guessed it would be, changing a single `searchParam`. So what it does is, it changes the `searchParams`, and trigger stores updates and adds a history item immediately.  But that turns out to be annoying when doing multiple `searchParam` changes, as you found out, because multiple history items will be there.
For multiple `searchParams` changes and then a single url history update, I recommend something very similar to what you're doing:

```
$url.searchParams.set('start', formatDate(newStart));
$url.searchParams.set('start', formatDate(newStart));
goto($url) // => pushes into history just once
```
I guess I should have described this in the docs and that would be cleared. So now I just did it and there is an example for this situation in the docs:

https://github.com/howesteve/elegua?tab=readme-ov-file#multiple-searchparam-changes

Would you please check if I was clear in the docs? It's late, I'm tired, might have been unclear.

Thanks
