### ISSUE TITLE
Persisting/restoring data between navigation

### ISSUE THREAD

**Issue by FluffyDiscord** [howesteve/elegua#5]
Right now this SPA router components lose their state when going backwards in history which makes it behave differently than most browsers, where going backwards shows page's last state, eg. with filled form fields, different opened tabs, changed element positions or states, the page scroll position, etc (theres a lot to consider!)

Currently we have to implement this logic ourself - creating history store, with derived stores per page/component/path, track path/url changes, then manage the page state/history by cloning, pushing and restoring the states from this history store.

It would be nice if this library provided it's own build store/logic that does that that we can use.

**Comment by howesteve** [comment]
What kind of logic do you think it should be implemented? Isn't what you want just a [$path](https://github.com/howesteve/elegua#path) subscription?

```ts
let state = {}
path.subscribe(x=>{
  state[path] = saveState()
})
```

... or just a [popstate](https://developer.mozilla.org/en-US/docs/Web/API/PopStateEvent) event handler?

```ts
 addEventListener('popstate', (event: PopStateEvent) => {
   saveFormState()
  // ... or restoreFormState()
  });
```

For the specific tabs situation and other small state changes, you can use hash method as shown in the [demo](https://elegua.netlify.app/hash).

Personally, if form state has changed, I'm more for denying user navigation until they decide if they want to save or discard changes. Otherwise, user keeps navigating,do not realize changes are pending, and ands up forgetting about them. I'd say most applications follow this guidelines, too. 
That's why I implemented [preventChange()](https://github.com/howesteve/elegua#preventchange) and [preventUnload()](https://github.com/howesteve/elegua#preventunload).

I hope you do not mean [Elegua](https://github.com/howesteve/elegua) should infer all parameters of a page's state by itself and restore them. That would be way off it's scope.

**Comment by FluffyDiscord** [comment]
Maybe PR or, better yet, REPL with an eample would help to explain myself. I'll see what I can do.

Side note - would be nice to be able to listen/react to `popstate`.

Also it seems you are missing listener for  `searchParams.append()` https://github.com/howesteve/elegua/blob/master/src/lib/Elegua.ts#L43 Is that intentional?

**Comment by howesteve** [comment]
> Maybe PR or, better yet, REPL with an eample would help to explain myself. I'll see what I can do
Ok, I'll be waiting.

> Side note - would be nice to be able to listen/react to popstate.
But you can, nothing blocking you from that:

```ts
document.addEventListener('popstate', (event: PopStateEvent) => {
   //...
  });
```
> Also it seems you are missing listener for searchParams.append()
Indeed, thanks for pointing it! I've just release v.2.21 with support for it.

**Comment by FluffyDiscord** [comment]
Would this be considered as "out of scope"? https://github.com/howesteve/elegua/pull/6

**Comment by howesteve** [comment]
Ops, forgot to answer this issue. Thanks for the PR, but I'm declining it this since it's so easy to implement through stores, and it's a very particular use case. I'm not getting this into the core. Btw, there was no need to be offended over the "out of scope" thing.
